/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all projects */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /** Create a new project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProject"];
                };
            };
            responses: {
                /** @description Project created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Update project */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProject"];
                };
            };
            responses: {
                /** @description Project updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        post?: never;
        /** Delete project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get students assigned to project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of students assigned to project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolUser"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Update all students assigned to project */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectStudents"];
                };
            };
            responses: {
                /** @description Project students updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolUser"][];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Add student to project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddStudentToProject"];
                };
            };
            responses: {
                /** @description Student added to project successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectStudent"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove student from project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    studentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Student removed from project successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all schools */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of schools */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /** Create a new school */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSchool"];
                };
            };
            responses: {
                /** @description School created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get school by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description School details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Update school */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSchool"];
                };
            };
            responses: {
                /** @description School updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["School"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        post?: never;
        /** Delete school */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description School deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get students by school ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of students in school */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolUser"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get teachers by school ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of teachers in school */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchoolUser"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        /** Update user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUser"];
                };
            };
            responses: {
                /** @description User updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        post?: never;
        /** Delete user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                403: components["responses"]["ForbiddenError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Project status
         * @enum {string}
         */
        Status: "draft" | "submitted" | "locked" | "public";
        UserRole: {
            /** Format: int64 */
            id: number;
            name: string;
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateUserRole: {
            name: string;
            description?: string;
        };
        UpdateUserRole: {
            name?: string;
            description?: string;
        };
        School: {
            /** Format: int64 */
            id: number;
            name: string;
            domain: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSchool: {
            name: string;
            domain: string;
        };
        UpdateSchool: {
            name?: string;
            domain?: string;
        };
        SchoolUser: {
            /** Format: int64 */
            id: number;
            /** Format: email */
            email: string;
            first_name?: string | null;
            last_name?: string | null;
            /** Format: int64 */
            school_id: number;
            /** Format: int64 */
            role_id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSchoolUser: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            /** Format: int64 */
            school_id: number;
            /** Format: int64 */
            role_id: number;
        };
        UpdateSchoolUser: {
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** Format: int64 */
            school_id?: number;
            /** Format: int64 */
            role_id?: number;
        };
        ProjectStudent: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            student_id: number;
            /** Format: date-time */
            created_at: string;
            students?: components["schemas"]["SchoolUser"];
        };
        Project: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            supervisor_id: number;
            /** Format: int64 */
            opponent_id: number;
            subject: string;
            description?: string | null;
            main_document?: string | null;
            /** Format: date-time */
            locked_until?: string | null;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            project_students?: components["schemas"]["ProjectStudent"][];
            school_users_projects_supervisor_idToschool_users?: components["schemas"]["SchoolUser"];
            school_users_projects_opponent_idToschool_users?: components["schemas"]["SchoolUser"];
        };
        CreateProject: {
            title: string;
            /** Format: int64 */
            supervisor_id: number;
            /** Format: int64 */
            opponent_id: number;
            subject: string;
            description?: string;
            main_document?: string;
            /** Format: date-time */
            locked_until?: string;
            status?: components["schemas"]["Status"];
        };
        UpdateProject: {
            title?: string;
            /** Format: int64 */
            supervisor_id?: number;
            /** Format: int64 */
            opponent_id?: number;
            subject?: string;
            description?: string;
            main_document?: string;
            /** Format: date-time */
            locked_until?: string;
            status?: components["schemas"]["Status"];
        };
        AddStudentToProject: {
            /** Format: int64 */
            studentId: number;
        };
        UpdateProjectStudents: {
            studentIds: number[];
        };
        Review: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            reviewer_id: number;
            comments: string;
            /** Format: date-time */
            submitted_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateReview: {
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            reviewer_id: number;
            comments: string;
        };
        UpdateReview: {
            comments: string;
        };
        Attachment: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id?: number | null;
            filename: string;
            storage_path: string;
            description?: string | null;
            /** Format: date-time */
            uploaded_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateAttachment: {
            /** Format: int64 */
            project_id?: number;
            filename: string;
            storage_path: string;
            description?: string;
        };
        UpdateAttachment: {
            filename?: string;
            description?: string;
        };
        ExternalLink: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id?: number | null;
            /** Format: uri */
            url?: string | null;
            title?: string | null;
            description?: string | null;
            /** Format: date-time */
            added_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateExternalLink: {
            /** Format: int64 */
            project_id?: number;
            /** Format: uri */
            url?: string;
            title?: string;
            description?: string;
        };
        UpdateExternalLink: {
            /** Format: int64 */
            project_id?: number;
            /** Format: uri */
            url?: string;
            title?: string;
            description?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: string;
            /** Format: int64 */
            school_id?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateUser: {
            /** Format: email */
            email: string;
            /** @default student */
            role: string;
            /** Format: int64 */
            school_id?: number;
        };
        UpdateUser: {
            role?: string;
            /** Format: int64 */
            school_id?: number;
        };
        Error: {
            error: string;
        };
        ValidationError: {
            error: string;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: {
        /** @description Authentication information is missing or invalid */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Unauthorized"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access forbidden */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Forbidden"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Not found"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Validation failed",
                 *       "details": [
                 *         {
                 *           "field": "title",
                 *           "message": "Title is required"
                 *         }
                 *       ]
                 *     } */
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description Internal server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Internal server error"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
