/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        audit_log_entries: {
            instance_id?: string;
            id: string;
            payload?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
            ip_address: string;
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        flow_state: {
            id: string;
            user_id?: string;
            auth_code: string;
            code_challenge_method: components["schemas"]["code_challenge_method"];
            code_challenge: string;
            provider_type: string;
            provider_access_token?: string;
            provider_refresh_token?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            authentication_method: string;
            /** Format: date-time */
            auth_code_issued_at?: string;
            saml_relay_states: components["schemas"]["saml_relay_states"][];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        identities: {
            provider_id: string;
            user_id: string;
            identity_data: Record<string, never>;
            provider: string;
            /** Format: date-time */
            last_sign_in_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            email?: string;
            id: string;
            users: components["schemas"]["users"];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        instances: {
            id: string;
            uuid?: string;
            raw_base_config?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        mfa_amr_claims: {
            session_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            authentication_method: string;
            id: string;
            sessions: components["schemas"]["sessions"];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        mfa_challenges: {
            id: string;
            factor_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            verified_at?: string;
            ip_address: string;
            otp_code?: string;
            web_authn_session_data?: Record<string, never>;
            mfa_factors: components["schemas"]["mfa_factors"];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        mfa_factors: {
            id: string;
            user_id: string;
            friendly_name?: string;
            factor_type: components["schemas"]["factor_type"];
            status: components["schemas"]["factor_status"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            secret?: string;
            phone?: string;
            /** Format: date-time */
            last_challenged_at?: string;
            web_authn_credential?: Record<string, never>;
            web_authn_aaguid?: string;
            mfa_challenges: components["schemas"]["mfa_challenges"][];
            users: components["schemas"]["users"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info. */
        oauth_authorizations: {
            id: string;
            authorization_id: string;
            client_id: string;
            user_id?: string;
            redirect_uri: string;
            scope: string;
            state?: string;
            resource?: string;
            code_challenge?: string;
            code_challenge_method?: components["schemas"]["code_challenge_method"];
            response_type: components["schemas"]["oauth_response_type"];
            status: components["schemas"]["oauth_authorization_status"];
            authorization_code?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            approved_at?: string;
            oauth_clients: components["schemas"]["oauth_clients"];
            users?: components["schemas"]["users"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info. */
        oauth_clients: {
            id: string;
            client_secret_hash?: string;
            registration_type: components["schemas"]["oauth_registration_type"];
            redirect_uris: string;
            grant_types: string;
            client_name?: string;
            client_uri?: string;
            logo_uri?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
            client_type: components["schemas"]["oauth_client_type"];
            oauth_authorizations: components["schemas"]["oauth_authorizations"][];
            oauth_consents: components["schemas"]["oauth_consents"][];
            sessions: components["schemas"]["sessions"][];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info. */
        oauth_consents: {
            id: string;
            user_id: string;
            client_id: string;
            scopes: string;
            /** Format: date-time */
            granted_at: string;
            /** Format: date-time */
            revoked_at?: string;
            oauth_clients: components["schemas"]["oauth_clients"];
            users: components["schemas"]["users"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        one_time_tokens: {
            id: string;
            user_id: string;
            token_type: components["schemas"]["one_time_token_type"];
            token_hash: string;
            relates_to: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            users: components["schemas"]["users"];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        refresh_tokens: {
            instance_id?: string;
            /** Format: int64 */
            id: number;
            token?: string;
            user_id?: string;
            revoked?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            parent?: string;
            session_id?: string;
            sessions?: components["schemas"]["sessions"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        saml_providers: {
            id: string;
            sso_provider_id: string;
            entity_id: string;
            metadata_xml: string;
            metadata_url?: string;
            attribute_mapping?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            name_id_format?: string;
            sso_providers: components["schemas"]["sso_providers"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        saml_relay_states: {
            id: string;
            sso_provider_id: string;
            request_id: string;
            for_email?: string;
            redirect_to?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            flow_state_id?: string;
            flow_state?: components["schemas"]["flow_state"];
            sso_providers: components["schemas"]["sso_providers"];
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        schema_migrations: {
            version: string;
        };
        /** @description This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        sessions: {
            id: string;
            user_id: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            factor_id?: string;
            aal?: components["schemas"]["aal_level"];
            /** Format: date-time */
            not_after?: string;
            /** Format: date-time */
            refreshed_at?: string;
            user_agent?: string;
            ip?: string;
            tag?: string;
            oauth_client_id?: string;
            mfa_amr_claims: components["schemas"]["mfa_amr_claims"][];
            refresh_tokens: components["schemas"]["refresh_tokens"][];
            oauth_clients?: components["schemas"]["oauth_clients"];
            users: components["schemas"]["users"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
         *     This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info. */
        sso_domains: {
            id: string;
            sso_provider_id: string;
            domain: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            sso_providers: components["schemas"]["sso_providers"];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
         *     This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info. */
        sso_providers: {
            id: string;
            resource_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            disabled?: boolean;
            saml_providers: components["schemas"]["saml_providers"][];
            saml_relay_states: components["schemas"]["saml_relay_states"][];
            sso_domains: components["schemas"]["sso_domains"][];
        };
        /** @description This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
         *     This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
         *     This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
         *     This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info. */
        users: {
            instance_id?: string;
            id: string;
            aud?: string;
            role?: string;
            email?: string;
            encrypted_password?: string;
            /** Format: date-time */
            email_confirmed_at?: string;
            /** Format: date-time */
            invited_at?: string;
            confirmation_token?: string;
            /** Format: date-time */
            confirmation_sent_at?: string;
            recovery_token?: string;
            /** Format: date-time */
            recovery_sent_at?: string;
            email_change_token_new?: string;
            email_change?: string;
            /** Format: date-time */
            email_change_sent_at?: string;
            /** Format: date-time */
            last_sign_in_at?: string;
            raw_app_meta_data?: Record<string, never>;
            raw_user_meta_data?: Record<string, never>;
            is_super_admin?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            phone?: string;
            /** Format: date-time */
            phone_confirmed_at?: string;
            phone_change?: string;
            phone_change_token?: string;
            /** Format: date-time */
            phone_change_sent_at?: string;
            /** Format: date-time */
            confirmed_at?: string;
            email_change_token_current?: string;
            /** Format: int32 */
            email_change_confirm_status?: number;
            /** Format: date-time */
            banned_until?: string;
            reauthentication_token?: string;
            /** Format: date-time */
            reauthentication_sent_at?: string;
            is_sso_user: boolean;
            /** Format: date-time */
            deleted_at?: string;
            is_anonymous: boolean;
            identities: components["schemas"]["identities"][];
            mfa_factors: components["schemas"]["mfa_factors"][];
            oauth_authorizations: components["schemas"]["oauth_authorizations"][];
            oauth_consents: components["schemas"]["oauth_consents"][];
            one_time_tokens: components["schemas"]["one_time_tokens"][];
            sessions: components["schemas"]["sessions"][];
            grades: components["schemas"]["grades"][];
            project_students: components["schemas"]["project_students"][];
            projects_projects_opponent_idTousers: components["schemas"]["projects"][];
            projects_projects_supervisor_idTousers: components["schemas"]["projects"][];
            reviews: components["schemas"]["reviews"][];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        attachments: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id?: number;
            filename: string;
            storage_path: string;
            description?: string;
            /** Format: date-time */
            uploaded_at: string;
            /** Format: date-time */
            updated_at: string;
            projects?: components["schemas"]["projects"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        external_links: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id?: number;
            url?: string;
            title?: string;
            description?: string;
            /** Format: date-time */
            added_at: string;
            /** Format: date-time */
            updated_at: string;
            projects?: components["schemas"]["projects"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        grades: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            value: number;
            /** Format: int64 */
            year_id: number;
            /** Format: int64 */
            project_id: number;
            reviewer_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            scale_id?: number;
            projects: components["schemas"]["projects"];
            years: components["schemas"]["years"];
            users: components["schemas"]["users"];
            scales?: components["schemas"]["scales"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        project_students: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            student_id: string;
            /** Format: date-time */
            created_at?: string;
            projects: components["schemas"]["projects"];
            users: components["schemas"]["users"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        projects: {
            /** Format: int64 */
            id: number;
            title: string;
            supervisor_id: string;
            opponent_id: string;
            subject: string;
            description?: string;
            main_documentation?: string;
            /** Format: date-time */
            updated_at: string;
            attachments: components["schemas"]["attachments"][];
            external_links: components["schemas"]["external_links"][];
            grades: components["schemas"]["grades"][];
            project_students: components["schemas"]["project_students"][];
            users_projects_opponent_idTousers: components["schemas"]["users"];
            users_projects_supervisor_idTousers: components["schemas"]["users"];
            reviews: components["schemas"]["reviews"][];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        reviews: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            reviewer_id: string;
            comments: string;
            /** Format: date-time */
            submitted_at: string;
            /** Format: date-time */
            updated_at: string;
            projects: components["schemas"]["projects"];
            users: components["schemas"]["users"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        roles: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: date-time */
            created_at: string;
            description?: string;
            /** Format: date-time */
            updated_at: string;
            scale_sets: components["schemas"]["scale_sets"][];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        scale_set_scales: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            scale_set_id: number;
            /** Format: int64 */
            scale_id: number;
            /** Format: int32 */
            weight: number;
            /** Format: int32 */
            display_order?: number;
            /** Format: date-time */
            created_at: string;
            scales: components["schemas"]["scales"];
            scale_sets: components["schemas"]["scale_sets"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        scale_sets: {
            /** Format: int64 */
            id: number;
            name?: string;
            /** Format: int64 */
            role_id?: number;
            /** Format: int64 */
            year_id?: number;
            /** Format: date-time */
            created_at: string;
            scale_set_scales: components["schemas"]["scale_set_scales"][];
            roles?: components["schemas"]["roles"];
            years?: components["schemas"]["years"];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        scales: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            maxVal: number;
            name: string;
            desc?: string;
            /** Format: date-time */
            created_at: string;
            grades: components["schemas"]["grades"][];
            scale_set_scales: components["schemas"]["scale_set_scales"][];
        };
        /** @description This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info. */
        years: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            school_id?: number;
            /** Format: date-time */
            assignment_date?: string;
            /** Format: date-time */
            submission_date?: string;
            /** Format: date-time */
            feedback_date?: string;
            /** Format: date-time */
            created_at: string;
            grades: components["schemas"]["grades"][];
            scale_sets: components["schemas"]["scale_sets"][];
        };
        /** @enum {string} */
        aal_level: "aal1" | "aal2" | "aal3";
        /** @enum {string} */
        code_challenge_method: "s256" | "plain";
        /** @enum {string} */
        factor_status: "unverified" | "verified";
        /** @enum {string} */
        factor_type: "totp" | "webauthn" | "phone";
        /** @enum {string} */
        oauth_authorization_status: "pending" | "approved" | "denied" | "expired";
        /** @enum {string} */
        oauth_client_type: "public" | "confidential";
        /** @enum {string} */
        oauth_registration_type: "dynamic" | "manual";
        /** @enum {string} */
        oauth_response_type: "code";
        /** @enum {string} */
        one_time_token_type: "confirmation_token" | "reauthentication_token" | "recovery_token" | "email_change_token_new" | "email_change_token_current" | "phone_change_token";
        /** @enum {string} */
        status: "draft" | "submitted" | "locked" | "public";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
